In [51]:
# Dependencies and Setup
%matplotlib inline
import matplotlib.pyplot as plt
import pandas as pd
import numpy as np

# Hide warning messages in notebook
import warnings
warnings.filterwarnings('ignore')

# File to Load (Remember to Change These)
mouse_data_csv = "data/mouse_drug_data.csv"
clin_data_csv = "data/clinicaltrial_data.csv"

# Read the Mouse and Drug Data and the Clinical Trial Data
mouse_df = pd.read_csv(mouse_data_csv)
clinical_df = pd.read_csv(clin_data_csv)
clinical_df.head()

  Mouse ID  Timepoint  Tumor Volume (mm3)  Metastatic Sites
0     b128          0                45.0                 0
1     f932          0                45.0                 0
2     g107          0                45.0                 0
3     a457          0                45.0                 0
4     c819          0                45.0                 0

In [52]:
# Combine the data into a single dataset
df = mouse_df.merge(clinical_df,on="Mouse ID")

# Display the data table for preview
df

     Mouse ID      Drug  Timepoint  Tumor Volume (mm3)  Metastatic Sites
0        f234  Stelasyn          0           45.000000                 0
1        f234  Stelasyn          5           47.313491                 0
2        f234  Stelasyn         10           47.904324                 0
3        f234  Stelasyn         15           48.735197                 1
4        f234  Stelasyn         20           51.112713                 2
5        f234  Stelasyn         25           52.178602                 2
6        f234  Stelasyn         30           56.873817                 2
7        f234  Stelasyn         35           57.748758                 2
8        x402  Stelasyn          0           45.000000                 0
9        x402  Stelasyn          5           46.327570                 1
10       x402  Stelasyn         10           46.886962                 1
11       x402  Stelasyn         15           49.119948                 1
12       x402  Stelasyn         20           50.414750                 2
13       x402  Stelasyn         25           52.431737                 2
14       x402  Stelasyn         30           54.351585                 3
15       x402  Stelasyn         35           55.240962                 3
16       x402  Stelasyn         40           56.691723                 3
17       x402  Stelasyn         45           61.619606                 3
18       a492  Stelasyn          0           45.000000                 0
19       a492  Stelasyn          5           46.409143                 0
20       a492  Stelasyn         10           48.432197                 0
21       a492  Stelasyn         15           51.985263                 0
22       a492  Stelasyn         20           53.677193                 0
23       a492  Stelasyn         25           54.701229                 1
24       a492  Stelasyn         30           56.201041                 1
25       a492  Stelasyn         35           57.308554                 1
26       a492  Stelasyn         40           57.928499                 1
27       a492  Stelasyn         45           60.122011                 1
28       w540  Stelasyn          0           45.000000                 0
29       w540  Stelasyn          5           45.885370                 1
...       ...       ...        ...                 ...               ...
1876     i669   Placebo         25           53.303185                 2
1877     r850   Placebo          0           45.000000                 0
1878     r850   Placebo          5           46.862912                 0
1879     r850   Placebo         10           48.515091                 1
1880     r850   Placebo         15           50.218605                 1
1881     a262   Placebo          0           45.000000                 0
1882     a262   Placebo          5           48.717568                 1
1883     a262   Placebo         10           49.595181                 1
1884     a262   Placebo         15           53.827974                 2
1885     a262   Placebo         20           57.013313                 2
1886     a262   Placebo         25           60.131862                 2
1887     a262   Placebo         30           64.958092                 3
1888     a262   Placebo         35           66.561963                 4
1889     a262   Placebo         40           69.592732                 4
1890     a262   Placebo         45           70.717621                 4
1891     q787   Placebo          0           45.000000                 0
1892     q787   Placebo          5           47.116616                 0
1893     q787   Placebo         10           48.593862                 1
1894     q787   Placebo         15           49.217732                 2
1895     q787   Placebo         20           50.229934                 2
1896     q787   Placebo         25           52.713188                 2
1897     q787   Placebo         30           55.036206                 2
1898     q787   Placebo         35           60.333852                 3
1899     q787   Placebo         40           62.034127                 3
1900     q787   Placebo         45           66.096475                 3
1901     j235   Placebo          0           45.000000                 0
1902     j235   Placebo          5           46.588820                 0
1903     j235   Placebo         10           48.018788                 1
1904     j235   Placebo         15           51.161138                 1
1905     j235   Placebo         20           52.942902                 1

[1906 rows x 5 columns]

## Tumor Response to Treatment

In [76]:
# Store the Mean Tumor Volume Data Grouped by Drug and Timepoint 
tumor_df = df.groupby(["Drug","Timepoint"]).agg({"Tumor Volume (mm3)":"mean"})
tumor_df
# Convert to DataFrame

# Preview DataFrame

                     Tumor Volume (mm3)
Drug      Timepoint
Capomulin 0                   45.000000
          5                   44.266086
          10                  43.084291
          15                  42.064317
          20                  40.716325
          25                  39.939528
          30                  38.769339
          35                  37.816839
          40                  36.958001
          45                  36.236114
Ceftamin  0                   45.000000
          5                   46.503051
          10                  48.285125
          15                  50.094055
          20                  52.157049
          25                  54.287674
          30                  56.769517
          35                  58.827548
          40                  61.467895
          45                  64.132421
Infubinol 0                   45.000000
          5                   47.062001
          10                  49.403909
          15                  51.296397
          20                  53.197691
          25                  55.715252
          30                  58.299397
          35                  60.742461
          40                  63.162824
          45                  65.755562
...                                 ...
Ramicane  0                   45.000000
          5                   43.944859
          10                  42.531957
          15                  41.495061
          20                  40.238325
          25                  38.974300
          30                  38.703137
          35                  37.451996
          40                  36.574081
          45                  34.955595
Stelasyn  0                   45.000000
          5                   47.527452
          10                  49.463844
          15                  51.529409
          20                  54.067395
          25                  56.166123
          30                  59.826738
          35                  62.440699
          40                  65.356386
          45                  68.438310
Zoniferol 0                   45.000000
          5                   46.851818
          10                  48.689881
          15                  50.779059
          20                  53.170334
          25                  55.432935
          30                  57.713531
          35                  60.089372
          40                  62.916692
          45                  65.960888

[100 rows x 1 columns]

In [54]:
# Store the Standard Error of Tumor Volumes Grouped by Drug and Timepoint

# Convert to DataFrame

# Preview DataFrame

In [55]:
# Minor Data Munging to Re-Format the Data Frames

# Preview that Reformatting worked

In [56]:
# Generate the Plot (with Error Bars)

# Save the Figure

In [57]:
# Show the Figure
plt.show()

## Metastatic Response to Treatment

In [58]:
# Store the Mean Met. Site Data Grouped by Drug and Timepoint 

# Convert to DataFrame

# Preview DataFrame

In [59]:
# Store the Standard Error associated with Met. Sites Grouped by Drug and Timepoint 

# Convert to DataFrame

# Preview DataFrame

In [60]:
# Minor Data Munging to Re-Format the Data Frames

# Preview that Reformatting worked

In [61]:
# Generate the Plot (with Error Bars)

# Save the Figure

# Show the Figure

## Survival Rates

In [62]:
# Store the Count of Mice Grouped by Drug and Timepoint (W can pass any metric)

# Convert to DataFrame

# Preview DataFrame

In [63]:
# Minor Data Munging to Re-Format the Data Frames

# Preview the Data Frame

In [64]:
# Generate the Plot (Accounting for percentages)

# Save the Figure

# Show the Figure
plt.show()

## Summary Bar Graph

In [65]:
# Calculate the percent changes for each drug

# Display the data to confirm

In [66]:
# Store all Relevant Percent Changes into a Tuple


# Splice the data between passing and failing drugs


# Orient widths. Add labels, tick marks, etc. 


# Use functions to label the percentages of changes


# Call functions to implement the function calls


# Save the Figure


# Show the Figure
fig.show()

NameError: name 'fig' is not defined